name = "NeutralLandscapes"
uuid = "71847384-8354-4223-ac08-659a5128069f"
authors = ["Timothée Poisot <timothee.poisot@umontreal.ca>", "Michael Krabbe Borregaard <mkborregaard@sund.ku.dk>", "Michael David Catchen <michael.catchen@mail.mcgill.ca>", "Rafael Schouten <rafaelschouten@gmail.com>", "Virgile Baudrot <virgile.baudrot@posteo.net>"]
version = "0.1.6"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HaltonSequences = "13907d55-377f-55d6-a9d6-25ac19e11b95"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataStructures = "0.18"
Distributions = "0.25"
HaltonSequences = "0.2"
NaNMath = "0.3, 1.0"
NearestNeighbors = "0.4"
StatsBase = "0.3, 0.34"
julia = "1.9"
